// Single source of truth for every approved Version 1 route. Consumed by
// vite.config.js (rollupOptions.input + the page-composer plugin),
// scripts/validate-routes.mjs, and scripts/verify-build-output.mjs.
export const routes = [
  { key: 'home', path: '/', entry: 'index.html', navKey: 'home', template: 'standard', content: 'home' },
  {
    key: 'solutions',
    path: '/solutions/',
    entry: 'solutions/index.html',
    navKey: 'solutions',
    template: 'standard',
    content: 'solutions',
  },
  {
    key: 'process',
    path: '/process/',
    entry: 'process/index.html',
    navKey: 'process',
    template: 'standard',
    content: 'process',
  },
  { key: 'work', path: '/work/', entry: 'work/index.html', navKey: 'work', template: 'listing', content: 'work' },
  {
    key: 'work-fes-challenger',
    path: '/work/fes-challenger/',
    entry: 'work/fes-challenger/index.html',
    navKey: 'work',
    template: 'case-study',
    content: 'work-fes-challenger',
  },
  {
    key: 'work-business-workflow-system',
    path: '/work/business-workflow-system/',
    entry: 'work/business-workflow-system/index.html',
    navKey: 'work',
    template: 'case-study',
    content: 'work-business-workflow-system',
  },
  {
    key: 'work-ebarangay',
    path: '/work/ebarangay/',
    entry: 'work/ebarangay/index.html',
    navKey: 'work',
    template: 'case-study',
    content: 'work-ebarangay',
  },
  { key: 'about', path: '/about/', entry: 'about/index.html', navKey: 'about', template: 'standard', content: 'about' },
  {
    key: 'contact',
    path: '/contact/',
    entry: 'contact/index.html',
    navKey: 'contact',
    template: 'standard',
    content: 'contact',
  },
  {
    key: 'privacy',
    path: '/privacy/',
    entry: 'privacy/index.html',
    navKey: null,
    template: 'standard',
    content: 'privacy',
  },
  {
    key: 'not-found',
    path: '/404.html',
    entry: '404.html',
    navKey: null,
    template: 'standard',
    content: 'not-found',
  },
];
